### ISSUE TITLE
Add "Send Account Information" functionality to Administration Panel

### ISSUE THREAD

**Issue by andreas-holzer** [lanoxx/masterylearning#28]
It would be easiest if we can automatically send the account information to new users by just clicking a button or during creation of the account (I guess the password is only stored in a hashed version and might not be recoverable at another point of time).

**Comment by lanoxx** [comment]
At the moment when we actually create the new user the password is available as plain text, but once in the database it is stored as a secure (and salted) hash. So if we send the confirmation mail immediately on user creation, then we can send the plain text password to the user.

**Comment by andreas-holzer** [comment]
When we address this issue, we should also add an automatic password generation.
