### ISSUE TITLE
Flow-Problem with yes-no-exercise

### ISSUE THREAD

**Issue by andreas-holzer** [lanoxx/masterylearning#9]
When I use the course from "Add Large Course", then for the last exercise, the text whether it is correct or not appears after a section title which should come later.

**Comment by lanoxx** [comment]
That is not hard coded text, but part of the data from the correct/incorrect links of the exercise. To show it earlier the data must be different.

Do you want to always display a text saying if the exercise was answered correctly or not before section title?

**Comment by lanoxx** [comment]
I think this can be closed. Please reopen if I am wrong.
